# Generated by Django 4.0.4 on 2022-05-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('SI', models.CharField(max_length=10)),
                ('GPA', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
