# Generated by Django 4.0.4 on 2022-05-23 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Thesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='DateOfBirth',
            field=models.DateField(default=datetime.datetime(2022, 5, 23, 0, 16, 31, 286965, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
