# Generated by Django 4.0.4 on 2022-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thesite', '0002_student_data_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='department',
            field=models.CharField(max_length=40),
        ),
    ]
