# Generated by Django 4.0.4 on 2022-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thesite', '0004_alter_student_data_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
